### ISSUE TITLE
Error in prune_LDM for CelebaHQ Dataset

### ISSUE THREAD

**Issue by Satyab23** [VainF/Diff-Pruning#10]
Dear Authors,
Thank you for sharing the amazing and inspiring pruning work! 

As mentioned in [celebahq-ldm-vq-4.yaml](https://github.com/VainF/Diff-Pruning/blob/main/ldm_exp/configs/latent-diffusion/celebahq-ldm-vq-4.yaml#L59) line59, CelebaHQ is unconditional stage_config
While running the pruning, I am getting the following error:

Pruning ...
Traceback (most recent call last):
  File "prune_ldm_celeba.py", line 75, in <module>
    uc = model.get_learned_conditioning(
  File "/raid/akshay/satyabrat/DiffPruneLDM/Diff-Pruning/ldm_exp/ldm/models/diffusion/ddpm.py", line 561, in get_learned_conditioning
    c = self.cond_stage_model(c)
TypeError: 'NoneType' object is not callable

Command used to run: 
CUDA_VISIBLE_DEVICES=1 python [prune_ldm.py](https://github.com/VainF/Diff-Pruning/blob/main/ldm_exp/prune_ldm.py) --sparsity 0.3 --pruner random

Could you please **share your code and config for CelebaHQ** Dataset as reported in the paper.

**Comment by Satyab23** [comment]
Dear @VainF , 

Did you get the chance to look into it. Kindly look into it.
